### ISSUE TITLE
Technical Design - Identify CMSs for implementation of website

### ISSUE THREAD

**Issue by macdhuibh** [pykafe/pykafe#10]
Technical Design - Identify CMSs for implementation of website

## Steps
- [x] Create list of CMSs you'd like to use
- [x] Present options to rest of PyKafe
- [x] Decide on CMS for PyKafe Website

**Comment by PeteCoward** [comment]
https://github.com/pykafe/pykafe/wiki/Technical-Design

**Comment by PeteCoward** [comment]
Wagtail has been chosen!
