### ISSUE TITLE
Domain - Create short list for a new domain name for PyKafe

### ISSUE THREAD

**Issue by macdhuibh** [pykafe/pykafe#11]
Create short list for a new domain name for PyKafe.
For example
- pykafe.ninjas
- code.pizza
- py.coffee
- we-like-to-code-and-design-and-buildstuff.com

**Comment by PeteCoward** [comment]
1) What Domain should we use for PyKafe’s site
:one: pykafe.com
:two: pykafe.tl    `6`
@ony, @mario, @nando, @niko, @sandro, @jbot
:three: pykafe.org    `1`
@Ano
:four: pykafe.io    `1`
@jbot
:five: pykafe.coffee    `1`
@wicher

**Comment by PeteCoward** [comment]
The winner is pykafe.tl, created #12 to purchase the domain
