### ISSUE TITLE
Konteudu pajina dahuluk. 

### ISSUE THREAD

**Issue by PeteCoward** [pykafe/pykafe#20]
What is Pykafe? Who are Pykafe? Where is Pykafe?

**Comment by PeteCoward** [comment]
post a link to what you have done here @marobo

**Comment by marobo** [comment]
Home page mockups draft: https://app.moqups.com/E4l86VLbOe/edit/page/ad64222d5

**Comment by marobo** [comment]
I had a screenshot here but looks unclear, gray:

![image](https://user-images.githubusercontent.com/12780301/53475809-41902200-3ab4-11e9-8bbd-999500fe2d9f.png)

**Comment by PeteCoward** [comment]
For review with Pykafe team!

**Comment by PeteCoward** [comment]
@eraulo @MarioAP @joanico @Lebanan please review!
