### ISSUE TITLE
Build the editable home page

### ISSUE THREAD

**Issue by PeteCoward** [pykafe/pykafe#22]
![screen shot 2019-03-02 at 10 54 03](https://user-images.githubusercontent.com/1092029/53675440-8ea10d80-3cd9-11e9-9dd1-383cb740ea76.png)
Use wagtail to make the home page of pykafe editable

**Comment by joanico** [comment]
Presiza esplikasaun klean husi maun @PeteCoward konaba issue ida ne'e.
