### ISSUE TITLE
Pajina ba aprende lian programasaun Python

### ISSUE THREAD

**Issue by joanico** [pykafe/pykafe#40]
Presiza halo dezenu ba mockup

**Comment by joanico** [comment]
This an image of the design mockup.

![learning_programming](https://user-images.githubusercontent.com/12932898/60024162-3e0f4f00-96d2-11e9-95dd-289a8b315854.png)

**Comment by joanico** [comment]
@marioAP @marobo @eraullo @lebana favor halo revizaun ba mockup ida ne'e.

**Comment by eraulo** [comment]
@joanico se bele ita bele muda pagina ba modelo seluk tamba pagina ida ta halo ne'e hanesa hela ho pagina home page

**Comment by joanico** [comment]
Diak imi bele hare fali dezenu ida ne'e @eraulo @marobo @marioAP @Lebanan 

![learning](https://user-images.githubusercontent.com/12932898/61111226-0ec75300-a4c4-11e9-83ed-b7cb7ca8e9b7.png)

**Comment by eraulo** [comment]
@joanico desenho diak ona no bele kontinua ba iha implementasaun ba iha futuro mak ita sei hadiak diak liu tan ninia interface.
