### ISSUE TITLE
Design pykafe site - Create style guide

### ISSUE THREAD

**Issue by Lebanan** [pykafe/pykafe#6]
## Problem
What is it going to look like? 

## Solution 
We need to define what the PyKafe site will look like. This includes things like Color scheme, Logo, Font, Layout, etc.

## Conditions of Satisfaction
- [x] Colour scheme - google search colour palette
- [x] Logo - we need a logo to brand this website
- [x] Font
- [ ] Layout
- [x] Create a Style Guide and save it to the PyKafe Wiki
- [x] Include Style for interface elements, such as buttons

**Comment by PeteCoward** [comment]
https://drive.google.com/file/d/12nPrf28Tj2KQR86IXdVhkkRCI8Z8bsY7/view

**Comment by PeteCoward** [comment]
My suggestion for next steps is to make this style guide in html and css!
