### ISSUE TITLE
styling ba pajina learn

### ISSUE THREAD

**Issue by marobo** [pykafe/pykafe#63]
## overview 
agora dau-dauk pajina learn nian seidauk iha nia styling neebe diak, 
ita bele haree imajem iha kraik nee;
![image](https://user-images.githubusercontent.com/12780301/64904047-e72c7b00-d6fe-11e9-9b97-ab651ec9ec97.png)

## Conditions & Satisfactions
styling tenki hanesan mockup iha kraik nee:
![image](https://user-images.githubusercontent.com/12780301/64904037-b77d7300-d6fe-11e9-84d0-c907aadd5e0f.png)

**Comment by joanico** [comment]
@MarioAP  Ita bele hare ezemplu prismjs iha link ida ne'e:
https://github.com/FlipperPA/wagtailcodeblock
