### ISSUE TITLE
Hatama aktividade ba website

### ISSUE THREAD

**Issue by eraulo** [pykafe/pykafe#74]
Bele ona hatama aktividade pykafe

**Comment by marobo** [comment]
Related docs here: https://docs.google.com/document/d/1ul-eMXFzw5mfHMrxoa5ODVY4g7CwAVM6QVFeo9Y-o7o/edit

**Comment by eraulo** [comment]
@marobo hau hare diak ona maibe sabado ita bele apresenta ba ita hotu atu ami bele fo input.
