### ISSUE TITLE
Konteudu - Buka tutorial lian programasaun bazika ne'ebe diak.

### ISSUE THREAD

**Issue by Lebanan** [pykafe/pykafe#9]
## Problem 
We need course material to teach programming in Tetum

## Solutions 
Find a good basic programming course and translate lessons 

## conditions of satisfaction 
- [ ] Content - find a good basic programming course and translate lessons

**Comment by joanico** [comment]
Basic python tutorial :
https://www.tutorialspoint.com/python/index.htm
https://www.programiz.com/python-programming/

**Comment by jbot5000** [comment]
https://www.codecademy.com/catalog/language/python 
https://code.org/ said they would translate into Tetun

**Comment by joanico** [comment]
Desidi ona lao tuir dezenu tutorial https://www.tutorialspoint.com/
- @Lebanan 
- @marobo 
- @eraulo 
- @MarioAP 
- @joanico
